name: Trigger Branch Pushes

on:
  workflow_dispatch:

jobs:
  push-to-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          token: ${{ secrets.TRIGGER_PAT_AQWERTYUIOP48 }}

      - name: Configure Git User
        run: |
          git config --global user.name "aqwertyuiop48"
          git config --global user.email "aqwertyuiop48@hotmail.com"

      - name: Loop and Push Commits to Branches
        run: |
          BRANCHES=(
            "my-nextjs-app"
            "simple-http-server-kotlin"
            "simple-http-server"
            "ruby-http-server"
            "micronaut-kotlin"
            "helidon-demo-kotlin"
            "helidon-demo"
            "javalin-java-app"
            "my-javalin-app"
            "my-quarkus-kotlin-app"
            "my-vertx-app"
            "my-angular-app"
            "my-spring-app"
            "my-angular-app-main"
            "my-vertx-app-kotlin"
            "micronaut_java"
            "my-spring-boot-maven-app"
            "my-quarkus-java-app"
            "my-spring-boot-app"
            "my-ktor-app"
          )

          for branch in "${BRANCHES[@]}"; do
            echo "------------------------------------------------"
            echo "Switching to branch: $branch"
            echo "------------------------------------------------"
            
            # Checkout the remote branch
            git checkout -b "$branch" "origin/$branch" || git checkout "$branch" || { echo "Branch $branch not found, skipping..."; continue; }
            
            # FORCE VERCEL BY CHANGING A FILE
            date +%s > vercel-deploy-trigger.txt
            git add vercel-deploy-trigger.txt
            git commit -m "chore: force Vercel deployment update"
            
            # Push the commit
            git push origin "$branch"
            
            # Pause for 3 seconds to prevent Vercel rate-limiting
            sleep 3
          done
